<?php

function pet_menu() {
    $items = array();
    $items['monkey'] = array(
        'title' => "Monkey",
        'page callback' => 'display_monkey',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['elephant'] = array(
        'title'=> "Elephant",
        'page callback' => 'display_elephant',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function display_monkey(){
    return '<img src="/sites/all/modules/pet/spidermonkey.jpg">
    <p>For more information about the spider monkey, visit:
    <a href="http://animals.nationalgeographic.com/animals/mammals/spider-monkey/">this site</a>
    </p>
    ';
}

function display_elephant(){
    return '<img src="/sites/all/modules/pet/pygmyele.jpg">;
    <p>For more information about the Pygmy Elephant, visit
    <a href="http://www.worldwildlife.org/species/borneo-pygmy-elephant">this site</a>
    </p>
    ';
}
